name: mylab
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  rflutter_alert: ^2.0.2
  google_nav_bar: ^5.0.6
  google_fonts: ^6.1.0
  get: 4.6.6
  get_storage: 2.1.1
  image_picker: ^0.8.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/logo/icons/

